### ISSUE TITLE
make faild

### ISSUE THREAD

**Issue by pengpeng-lian** [The-OpenROAD-Project/OpenLane#1215]
### Description
jplian@rivai-u20-vm-intern:~/projects/OpenLane$ make
make[1]: Entering directory '/work/home/jplian/projects/OpenLane'
ab6b79bce7f928a9cec34ba672478398a83639e9: Pulling from efabless/openlane
Digest: sha256:36c2fb291a6c0173b637172f0429c44558d4deed3fd744b58247097f70901e60
Status: Image is up to date for efabless/openlane:ab6b79bce7f928a9cec34ba672478398a83639e9
docker.io/efabless/openlane:ab6b79bce7f928a9cec34ba672478398a83639e9
make[1]: Leaving directory '/work/home/jplian/projects/OpenLane'
./venv/bin/python3 -m pip install --upgrade --no-cache-dir volare
Requirement already up-to-date: volare in ./venv/lib/python3.8/site-packages (0.2.1)
Requirement already satisfied, skipping upgrade: click<9,>=8.0.0 in ./venv/lib/python3.8/site-packages (from volare) (8.1.3)
Requirement already satisfied, skipping upgrade: rich~=10.16.0 in ./venv/lib/python3.8/site-packages (from volare) (10.16.2)
Requirement already satisfied, skipping upgrade: click-default-group~=1.2.2 in ./venv/lib/python3.8/site-packages (from volare) (1.2.2)
Requirement already satisfied, skipping upgrade: pcpp~=1.30 in ./venv/lib/python3.8/site-packages (from volare) (1.30)
Requirement already satisfied, skipping upgrade: requests~=2.27.0 in ./venv/lib/python3.8/site-packages (from volare) (2.27.1)
Requirement already satisfied, skipping upgrade: pyyaml~=5.4.0 in ./venv/lib/python3.8/site-packages (from volare) (5.4.1)
Requirement already satisfied, skipping upgrade: pygments<3.0.0,>=2.6.0 in ./venv/lib/python3.8/site-packages (from rich~=10.16.0->volare) (2.12.0)
Requirement already satisfied, skipping upgrade: commonmark<0.10.0,>=0.9.0 in ./venv/lib/python3.8/site-packages (from rich~=10.16.0->volare) (0.9.1)
Requirement already satisfied, skipping upgrade: colorama<0.5.0,>=0.4.0 in ./venv/lib/python3.8/site-packages (from rich~=10.16.0->volare) (0.4.5)
Requirement already satisfied, skipping upgrade: charset-normalizer~=2.0.0; python_version >= "3" in ./venv/lib/python3.8/site-packages (from requests~=2.27.0->volare) (2.0.12)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from requests~=2.27.0->volare) (2022.6.15)
Requirement already satisfied, skipping upgrade: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests~=2.27.0->volare) (1.26.10)
Requirement already satisfied, skipping upgrade: idna<4,>=2.5; python_version >= "3" in ./venv/lib/python3.8/site-packages (from requests~=2.27.0->volare) (3.3)
./venv/bin/volare enable
[14:42:11] Found version 41c0908b47130d5675ff8484255b43f66463a7d6 in ./dependencies/tool_metadata.yml.                                                                                                                               common.py:131
Traceback (most recent call last):
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7ff3230028e0>: **Failed** to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, **error** or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /efabless/volare/releases/download/sky130-41c0908b47130d5675ff8484255b43f66463a7d6/default.tar.xz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff3230028e0>: **Failed** to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./venv/bin/volare", line 8, in <module>
    sys.exit(cli())
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/volare/manage.py", line 255, in enable_cmd
    enable(pdk_root=pdk_root, pdk=pdk, version=version)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/volare/manage.py", line 159, in enable
    status = requests.head(link).status_code
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/requests/api.py", line 102, in head
    return request('head', url, **kwargs)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/work/home/jplian/projects/OpenLane/venv/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /efabless/volare/releases/download/sky130-41c0908b47130d5675ff8484255b43f66463a7d6/default.tar.xz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff3230028e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
make: *** [Makefile:107: pdk] Error 1

### Reproduction Material
make

**Comment by vijayank88** [comment]
```
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /efabless/volare/releases/download/sky130-41c0908b47130d5675ff8484255b43f66463a7d6/default.tar.xz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff3230028e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```
Its seems network connection not stable

**Comment by pengpeng-lian** [comment]
> Thanks. I tried again, and he started downloading

**Comment by pengpeng-lian** [comment]
> ```
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /efabless/volare/releases/download/sky130-41c0908b47130d5675ff8484255b43f66463a7d6/default.tar.xz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff3230028e0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
> ```
> 
> Its seems network connection not stable
Found version 41c0908.....d6 in ./dependencies/tools_metadata.yml.
Downloading pre-built tarball for 41c0908.....d6...   ---------------------------------------- %9 1:41:02

**Comment by vijayank88** [comment]
@pengpeng-lian 
Once `make` completes without any issues, you may close this issue.
