### ISSUE TITLE
OpenLane first time installation problem

### ISSUE THREAD

**Issue by lcc0094** [The-OpenROAD-Project/OpenLane#1451]
## Description

Hi, I am installing OpenLane on Ubuntu 20.04 but I get this error:
```
Traceback (most recent call last):
  File "./venv/bin/volare", line 8, in <module>
    sys.exit(cli())
  File "/home/pc/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/pc/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/pc/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pc/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pc/OpenLane/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pc/OpenLane/venv/lib/python3.8/site-packages/volare/manage.py", line 320, in enable_cmd
    enable(pdk_root=pdk_root, pdk=pdk, version=version)
  File "/home/pc/OpenLane/venv/lib/python3.8/site-packages/volare/manage.py", line 253, in enable
    with tarfile.open(tarball_path, mode="r:*") as tf:
  File "/usr/local/lib/python3.8/tarfile.py", line 1604, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
make: *** [Makefile:112: pdk] Error 1
```

## Expected behavior

Install OpenLane on Ubuntu for the first time

## Environment

```
Kernel: Linux v5.15.0-52-generic
Distribution: ubuntu 20.04
Python: v3.8.3 (OK)
Container Engine: docker v20.10.20 (OK)
OpenLane Git Version: 63a6d0230a133810e756c4d4117dba2c1f926998
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: FAILED
/home/pc/OPLA/pdks/sky130A not found.
Traceback (most recent call last):
  File "/home/pc/OPLA/dependencies/verify_versions.py", line 72, in verify_versions
    raise Exception(f"{pdk_dir} not found.")
Exception: /home/pc/OPLA/pdks/sky130A not found.

Failed to verify sky130A.
---
Git Log (Last 3 Commits)

63a6d02 2022-10-25T10:36:13+02:00 Fix Synthesis Exploration (#1437) - vijayan -  (HEAD -> master, origin/master, origin/HEAD)
9197534 2022-10-25T09:36:14+02:00 fix usage command in docs (#1449) - Liu Yihua -  ()
5c58d41 2022-10-24T22:58:28+02:00 Various Abstractions for `config.json` (#1445) - Mohamed Gaber -  (tag: 2022.10.25)
---
Git Remotes

origin	https://github.com/The-OpenROAD-Project/OpenLane (fetch)
origin	https://github.com/The-OpenROAD-Project/OpenLane (push)


```

## Logs

```

```
I tried to install OpenLane in another folder, but I received the same error.

**Comment by donn** [comment]
Hello- there's been an update to the Volare tool. Can you try again now? Sorry for the long wait.
