### ISSUE TITLE
Running IO Placement stage fails

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#1497]
### Description

This is MPW CI [design](https://github.com/The-OpenROAD-Project/caravel_user_project/blob/SultanShadow/APPROX_MULT/openlane/user_proj_example/pin_order.cfg), follows pin order name with xyz.*

As its MPW6 design, designer specified only few pins in specific side and left some of pins to place randomly.

With latest OpenLane setup its made compulsory to define manual placement of IO pins or go with auto pin placement technique. To skip IO placement error for un-defined pin placement used `set ::env(FP_IO_UNMATCHED_ERROR) 0`.

After the following PR https://github.com/The-OpenROAD-Project/OpenLane/pull/1461 facing error again. Help me how to resolve the error.

### Expected Behavior

Flow pass IO placement stage.

### Environment report

```shell
Kernel: Linux v3.10.0-1160.49.1.el7.x86_64
Distribution: centos 7
Python: v3.6.8 (OK)
Container Engine: docker v20.10.16 (OK)
OpenLane Git Version: 1da2eec3d9b5a3612cb026cf9060cb7954e4c24a
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

1da2eec 2022-11-16T01:37:27+02:00 [BOT] Update netgen (#1452) - Openlane Bot -  (HEAD -> master, tag: 2022.11.16, origin/master, origin/HEAD)
77fd531 2022-11-15T13:32:13+02:00 Revert #1485 (#1492) - Mohamed Gaber -  ()
dbb2487 2022-11-15T13:05:26+02:00 [BOT] Update PDK (#1455) - Openlane Bot -  ()
---
Git Remotes

origin	https://github.com/The-OpenROAD-Project/OpenLane.git (fetch)
origin	https://github.com/The-OpenROAD-Project/OpenLane.git (push)
```

### Reproduction material

Unzip `APPROX_MULT.zip` 
[APPROX_MULT.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/10020308/APPROX_MULT.zip)
 and place it `OpenLane/designs/`

%cd OpenLane
%make mount
%./flow.tcl -design APPROX_MULT -verbose 99

### Relevant log output

```shell
[INFO]: Running IO Placement (log: logs/floorplan/4-place_io.log)...
OpenROAD fc0bc8eb8a2ad14a84e0235578ff94733fc108ab 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
Top-level design name: user_proj_example
Block boundaries: 0 0 900000 600000
Horizontal Tracks Origin: 340, Count: 882, Step: 680
Vertical Tracks Origin: 230, Count: 1956, Step: 460
Placement details for the #N side
Virtual pin count:  0
Actual pin count:  114
Total pin count:  114
Tracks count:  1956
Tracks per pin:  17
Used tracks count:  1922
Unused track count:  34
Starting track index:  17
Placement Map:
[230, 690, 1150, 1610, 2070, 2530, 2990, 3450, 3910, 4370, 4830, 5290, 5750, 6210, 6670, 7130, 7590, 8050, 8510, 8970, 9430, 9890, 10350, 10810, 11270, 11730, 12190, 12650, 13110, 13570, 14030, 14490, 14950, 15410, 15870, 16330, 16790, 17250, 17710, 18170, 18630, 19090, 19550, 20010, 20470, 20930, 21390, 21850, 22310, 22770, 23230, 23690, 24150, 24610, 25070, 25530, 25990, 26450, 26910, 27370, 27830, 28290, 28750, 29210, 29670, 30130, 30590, 31050, 31510, 31970, 32430, 32890, 33350, 33810, 34270, 34730, 35190, 35650, 36110, 36570, 37030, 37490, 37950, 38410, 38870, 39330, 39790, 40250, 40710, 41170, 41630, 42090, 42550, 43010, 43470, 43930, 44390, 44850, 45310, 45770, 46230, 46690, 47150, 47610, 48070, 48530, 48990, 49450, 49910, 50370, 50830, 51290, 51750, 52210, 52670, 53130, 53590, 54050, 54510, 54970, 55430, 55890, 56350, 56810, 57270, 57730, 58190, 58650, 59110, 59570, 60030, 60490, 60950, 61410, 61870, 62330, 62790, 63250, 63710, 64170, 64630, 65090, 65550, 66010, 66470, 66930, 67390, 67850, 68310, 68770, 69230, 69690, 70150, 70610, 71070, 71530, 71990, 72450, 72910, 73370, 73830, 74290, 74750, 75210, 75670, 76130, 76590, 77050, 77510, 77970, 78430, 78890, 79350, 79810, 80270, 80730, 81190, 81650, 82110, 82570, 83030, 83490, 83950, 84410, 84870, 85330, 85790, 86250, 86710, 87170, 87630, 88090, 88550, 89010, 89470, 89930, 90390, 90850, 91310, 91770, 92230, 92690, 93150, 93610, 94070, 94530, 94990, 95450, 95910, 96370, 96830, 97290, 97750, 98210, 98670, 99130, 99590, 100050, 100510, 100970, 101430, 101890, 102350, 102810, 103270, 103730, 104190, 104650, 105110, 105570, 106030, 106490, 106950, 107410, 107870, 108330, 108790, 109250, 109710, 110170, 110630, 111090, 111550, 112010, 112470, 112930, 113390, 113850, 114310, 114770, 115230, 115690, 116150, 116610, 117070, 117530, 117990, 118450, 118910, 119370, 119830, 120290, 120750, 121210, 121670, 122130, 122590, 123050, 123510, 123970, 124430, 124890, 125350, 125810, 126270, 126730, 127190, 127650, 128110, 128570, 129030, 129490, 129950, 130410, 130870, 131330, 131790, 132250, 132710, 133170, 133630, 134090, 134550, 135010, 135470, 135930, 136390, 136850, 137310, 137770, 138230, 138690, 139150, 139610, 140070, 140530, 140990, 141450, 141910, 142370, 142830, 143290, 143750, 144210, 144670, 145130, 145590, 146050, 146510, 146970, 147430, 147890, 148350, 148810, 149270, 149730, 150190, 150650, 151110, 151570, 152030, 152490, 152950, 153410, 153870, 154330, 154790, 155250, 155710, 156170, 156630, 157090, 157550, 158010, 158470, 158930, 159390, 159850, 160310, 160770, 161230, 161690, 162150, 162610, 163070, 163530, 163990, 164450, 164910, 165370, 165830, 166290, 166750, 167210, 167670, 168130, 168590, 169050, 169510, 169970, 170430, 170890, 171350, 171810, 172270, 172730, 173190, 173650, 174110, 174570, 175030, 175490, 175950, 176410, 176870, 177330, 177790, 178250, 178710, 179170, 179630, 180090, 180550, 181010, 181470, 181930, 182390, 182850, 183310, 183770, 184230, 184690, 185150, 185610, 186070, 186530, 186990, 187450, 187910, 188370, 188830, 189290, 189750, 190210, 190670, 191130, 191590, 192050, 192510, 192970, 193430, 193890, 194350, 194810, 195270, 195730, 196190, 196650, 197110, 197570, 198030, 198490, 198950, 199410, 199870, 200330, 200790, 201250, 201710, 202170, 202630, 203090, 203550, 204010, 204470, 204930, 205390, 205850, 206310, 206770, 207230, 207690, 208150, 208610, 209070, 209530, 209990, 210450, 210910, 211370, 211830, 212290, 212750, 213210, 213670, 214130, 214590, 215050, 215510, 215970, 216430, 216890, 217350, 217810, 218270, 218730, 219190, 219650, 220110, 220570, 221030, 221490, 221950, 222410, 222870, 223330, 223790, 224250, 224710, 225170, 225630, 226090, 226550, 227010, 227470, 227930, 228390, 228850, 229310, 229770, 230230, 230690, 231150, 231610, 232070, 232530, 232990, 233450, 233910, 234370, 234830, 235290, 235750, 236210, 236670, 237130, 237590, 238050, 238510, 238970, 239430, 239890, 240350, 240810, 241270, 241730, 242190, 242650, 243110, 243570, 244030, 244490, 244950, 245410, 245870, 246330, 246790, 247250, 247710, 248170, 248630, 249090, 249550, 250010, 250470, 250930, 251390, 251850, 252310, 252770, 253230, 253690, 254150, 254610, 255070, 255530, 255990, 256450, 256910, 257370, 257830, 258290, 258750, 259210, 259670, 260130, 260590, 261050, 261510, 261970, 262430, 262890, 263350, 263810, 264270, 264730, 265190, 265650, 266110, 266570, 267030, 267490, 267950, 268410, 268870, 269330, 269790, 270250, 270710, 271170, 271630, 272090, 272550, 273010, 273470, 273930, 274390, 274850, 275310, 275770, 276230, 276690, 277150, 277610, 278070, 278530, 278990, 279450, 279910, 280370, 280830, 281290, 281750, 282210, 282670, 283130, 283590, 284050, 284510, 284970, 285430, 285890, 286350, 286810, 287270, 287730, 288190, 288650, 289110, 289570, 290030, 290490, 290950, 291410, 291870, 292330, 292790, 293250, 293710, 294170, 294630, 295090, 295550, 296010, 296470, 296930, 297390, 297850, 298310, 298770, 299230, 299690, 300150, 300610, 301070, 301530, 301990, 302450, 302910, 303370, 303830, 304290, 304750, 305210, 305670, 306130, 306590, 307050, 307510, 307970, 308430, 308890, 309350, 309810, 310270, 310730, 311190, 311650, 312110, 312570, 313030, 313490, 313950, 314410, 314870, 315330, 315790, 316250, 316710, 317170, 317630, 318090, 318550, 319010, 319470, 319930, 320390, 320850, 321310, 321770, 322230, 322690, 323150, 323610, 324070, 324530, 324990, 325450, 325910, 326370, 326830, 327290, 327750, 328210, 328670, 329130, 329590, 330050, 330510, 330970, 331430, 331890, 332350, 332810, 333270, 333730, 334190, 334650, 335110, 335570, 336030, 336490, 336950, 337410, 337870, 338330, 338790, 339250, 339710, 340170, 340630, 341090, 341550, 342010, 342470, 342930, 343390, 343850, 344310, 344770, 345230, 345690, 346150, 346610, 347070, 347530, 347990, 348450, 348910, 349370, 349830, 350290, 350750, 351210, 351670, 352130, 352590, 353050, 353510, 353970, 354430, 354890, 355350, 355810, 356270, 356730, 357190, 357650, 358110, 358570, 359030, 359490, 359950, 360410, 360870, 361330, 361790, 362250, 362710, 363170, 363630, 364090, 364550, 365010, 365470, 365930, 366390, 366850, 367310, 367770, 368230, 368690, 369150, 369610, 370070, 370530, 370990, 371450, 371910, 372370, 372830, 373290, 373750, 374210, 374670, 375130, 375590, 376050, 376510, 376970, 377430, 377890, 378350, 378810, 379270, 379730, 380190, 380650, 381110, 381570, 382030, 382490, 382950, 383410, 383870, 384330, 384790, 385250, 385710, 386170, 386630, 387090, 387550, 388010, 388470, 388930, 389390, 389850, 390310, 390770, 391230, 391690, 392150, 392610, 393070, 393530, 393990, 394450, 394910, 395370, 395830, 396290, 396750, 397210, 397670, 398130, 398590, 399050, 399510, 399970, 400430, 400890, 401350, 401810, 402270, 402730, 403190, 403650, 404110, 404570, 405030, 405490, 405950, 406410, 406870, 407330, 407790, 408250, 408710, 409170, 409630, 410090, 410550, 411010, 411470, 411930, 412390, 412850, 413310, 413770, 414230, 414690, 415150, 415610, 416070, 416530, 416990, 417450, 417910, 418370, 418830, 419290, 419750, 420210, 420670, 421130, 421590, 422050, 422510, 422970, 423430, 423890, 424350, 424810, 425270, 425730, 426190, 426650, 427110, 427570, 428030, 428490, 428950, 429410, 429870, 430330, 430790, 431250, 431710, 432170, 432630, 433090, 433550, 434010, 434470, 434930, 435390, 435850, 436310, 436770, 437230, 437690, 438150, 438610, 439070, 439530, 439990, 440450, 440910, 441370, 441830, 442290, 442750, 443210, 443670, 444130, 444590, 445050, 445510, 445970, 446430, 446890, 447350, 447810, 448270, 448730, 449190, 449650, 450110, 450570, 451030, 451490, 451950, 452410, 452870, 453330, 453790, 454250, 454710, 455170, 455630, 456090, 456550, 457010, 457470, 457930, 458390, 458850, 459310, 459770, 460230, 460690, 461150, 461610, 462070, 462530, 462990, 463450, 463910, 464370, 464830, 465290, 465750, 466210, 466670, 467130, 467590, 468050, 468510, 468970, 469430, 469890, 470350, 470810, 471270, 471730, 472190, 472650, 473110, 473570, 474030, 474490, 474950, 475410, 475870, 476330, 476790, 477250, 477710, 478170, 478630, 479090, 479550, 480010, 480470, 480930, 481390, 481850, 482310, 482770, 483230, 483690, 484150, 484610, 485070, 485530, 485990, 486450, 486910, 487370, 487830, 488290, 488750, 489210, 489670, 490130, 490590, 491050, 491510, 491970, 492430, 492890, 493350, 493810, 494270, 494730, 495190, 495650, 496110, 496570, 497030, 497490, 497950, 498410, 498870, 499330, 499790, 500250, 500710, 501170, 501630, 502090, 502550, 503010, 503470, 503930, 504390, 504850, 505310, 505770, 506230, 506690, 507150, 507610, 508070, 508530, 508990, 509450, 509910, 510370, 510830, 511290, 511750, 512210, 512670, 513130, 513590, 514050, 514510, 514970, 515430, 515890, 516350, 516810, 517270, 517730, 518190, 518650, 519110, 519570, 520030, 520490, 520950, 521410, 521870, 522330, 522790, 523250, 523710, 524170, 524630, 525090, 525550, 526010, 526470, 526930, 527390, 527850, 528310, 528770, 529230, 529690, 530150, 530610, 531070, 531530, 531990, 532450, 532910, 533370, 533830, 534290, 534750, 535210, 535670, 536130, 536590, 537050, 537510, 537970, 538430, 538890, 539350, 539810, 540270, 540730, 541190, 541650, 542110, 542570, 543030, 543490, 543950, 544410, 544870, 545330, 545790, 546250, 546710, 547170, 547630, 548090, 548550, 549010, 549470, 549930, 550390, 550850, 551310, 551770, 552230, 552690, 553150, 553610, 554070, 554530, 554990, 555450, 555910, 556370, 556830, 557290, 557750, 558210, 558670, 559130, 559590, 560050, 560510, 560970, 561430, 561890, 562350, 562810, 563270, 563730, 564190, 564650, 565110, 565570, 566030, 566490, 566950, 567410, 567870, 568330, 568790, 569250, 569710, 570170, 570630, 571090, 571550, 572010, 572470, 572930, 573390, 573850, 574310, 574770, 575230, 575690, 576150, 576610, 577070, 577530, 577990, 578450, 578910, 579370, 579830, 580290, 580750, 581210, 581670, 582130, 582590, 583050, 583510, 583970, 584430, 584890, 585350, 585810, 586270, 586730, 587190, 587650, 588110, 588570, 589030, 589490, 589950, 590410, 590870, 591330, 591790, 592250, 592710, 593170, 593630, 594090, 594550, 595010, 595470, 595930, 596390, 596850, 597310, 597770, 598230, 598690, 599150, 599610, 600070, 600530, 600990, 601450, 601910, 602370, 602830, 603290, 603750, 604210, 604670, 605130, 605590, 606050, 606510, 606970, 607430, 607890, 608350, 608810, 609270, 609730, 610190, 610650, 611110, 611570, 612030, 612490, 612950, 613410, 613870, 614330, 614790, 615250, 615710, 616170, 616630, 617090, 617550, 618010, 618470, 618930, 619390, 619850, 620310, 620770, 621230, 621690, 622150, 622610, 623070, 623530, 623990, 624450, 624910, 625370, 625830, 626290, 626750, 627210, 627670, 628130, 628590, 629050, 629510, 629970, 630430, 630890, 631350, 631810, 632270, 632730, 633190, 633650, 634110, 634570, 635030, 635490, 635950, 636410, 636870, 637330, 637790, 638250, 638710, 639170, 639630, 640090, 640550, 641010, 641470, 641930, 642390, 642850, 643310, 643770, 644230, 644690, 645150, 645610, 646070, 646530, 646990, 647450, 647910, 648370, 648830, 649290, 649750, 650210, 650670, 651130, 651590, 652050, 652510, 652970, 653430, 653890, 654350, 654810, 655270, 655730, 656190, 656650, 657110, 657570, 658030, 658490, 658950, 659410, 659870, 660330, 660790, 661250, 661710, 662170, 662630, 663090, 663550, 664010, 664470, 664930, 665390, 665850, 666310, 666770, 667230, 667690, 668150, 668610, 669070, 669530, 669990, 670450, 670910, 671370, 671830, 672290, 672750, 673210, 673670, 674130, 674590, 675050, 675510, 675970, 676430, 676890, 677350, 677810, 678270, 678730, 679190, 679650, 680110, 680570, 681030, 681490, 681950, 682410, 682870, 683330, 683790, 684250, 684710, 685170, 685630, 686090, 686550, 687010, 687470, 687930, 688390, 688850, 689310, 689770, 690230, 690690, 691150, 691610, 692070, 692530, 692990, 693450, 693910, 694370, 694830, 695290, 695750, 696210, 696670, 697130, 697590, 698050, 698510, 698970, 699430, 699890, 700350, 700810, 701270, 701730, 702190, 702650, 703110, 703570, 704030, 704490, 704950, 705410, 705870, 706330, 706790, 707250, 707710, 708170, 708630, 709090, 709550, 710010, 710470, 710930, 711390, 711850, 712310, 712770, 713230, 713690, 714150, 714610, 715070, 715530, 715990, 716450, 716910, 717370, 717830, 718290, 718750, 719210, 719670, 720130, 720590, 721050, 721510, 721970, 722430, 722890, 723350, 723810, 724270, 724730, 725190, 725650, 726110, 726570, 727030, 727490, 727950, 728410, 728870, 729330, 729790, 730250, 730710, 731170, 731630, 732090, 732550, 733010, 733470, 733930, 734390, 734850, 735310, 735770, 736230, 736690, 737150, 737610, 738070, 738530, 738990, 739450, 739910, 740370, 740830, 741290, 741750, 742210, 742670, 743130, 743590, 744050, 744510, 744970, 745430, 745890, 746350, 746810, 747270, 747730, 748190, 748650, 749110, 749570, 750030, 750490, 750950, 751410, 751870, 752330, 752790, 753250, 753710, 754170, 754630, 755090, 755550, 756010, 756470, 756930, 757390, 757850, 758310, 758770, 759230, 759690, 760150, 760610, 761070, 761530, 761990, 762450, 762910, 763370, 763830, 764290, 764750, 765210, 765670, 766130, 766590, 767050, 767510, 767970, 768430, 768890, 769350, 769810, 770270, 770730, 771190, 771650, 772110, 772570, 773030, 773490, 773950, 774410, 774870, 775330, 775790, 776250, 776710, 777170, 777630, 778090, 778550, 779010, 779470, 779930, 780390, 780850, 781310, 781770, 782230, 782690, 783150, 783610, 784070, 784530, 784990, 785450, 785910, 786370, 786830, 787290, 787750, 788210, 788670, 789130, 789590, 790050, 790510, 790970, 791430, 791890, 792350, 792810, 793270, 793730, 794190, 794650, 795110, 795570, 796030, 796490, 796950, 797410, 797870, 798330, 798790, 799250, 799710, 800170, 800630, 801090, 801550, 802010, 802470, 802930, 803390, 803850, 804310, 804770, 805230, 805690, 806150, 806610, 807070, 807530, 807990, 808450, 808910, 809370, 809830, 810290, 810750, 811210, 811670, 812130, 812590, 813050, 813510, 813970, 814430, 814890, 815350, 815810, 816270, 816730, 817190, 817650, 818110, 818570, 819030, 819490, 819950, 820410, 820870, 821330, 821790, 822250, 822710, 823170, 823630, 824090, 824550, 825010, 825470, 825930, 826390, 826850, 827310, 827770, 828230, 828690, 829150, 829610, 830070, 830530, 830990, 831450, 831910, 832370, 832830, 833290, 833750, 834210, 834670, 835130, 835590, 836050, 836510, 836970, 837430, 837890, 838350, 838810, 839270, 839730, 840190, 840650, 841110, 841570, 842030, 842490, 842950, 843410, 843870, 844330, 844790, 845250, 845710, 846170, 846630, 847090, 847550, 848010, 848470, 848930, 849390, 849850, 850310, 850770, 851230, 851690, 852150, 852610, 853070, 853530, 853990, 854450, 854910, 855370, 855830, 856290, 856750, 857210, 857670, 858130, 858590, 859050, 859510, 859970, 860430, 860890, 861350, 861810, 862270, 862730, 863190, 863650, 864110, 864570, 865030, 865490, 865950, 866410, 866870, 867330, 867790, 868250, 868710, 869170, 869630, 870090, 870550, 871010, 871470, 871930, 872390, 872850, 873310, 873770, 874230, 874690, 875150, 875610, 876070, 876530, 876990, 877450, 877910, 878370, 878830, 879290, 879750, 880210, 880670, 881130, 881590, 882050, 882510, 882970, 883430, 883890, 884350, 884810, 885270, 885730, 886190, 886650, 887110, 887570, 888030, 888490, 888950, 889410, 889870, 890330, 890790, 891250, 891710, 892170, 892630, 893090, 893550, 894010, 894470, 894930, 895390, 895850, 896310, 896770, 897230, 897690, 898150, 898610, 899070, 899530, ]
Indices of used tracks: [17, 34, 51, 68, 85, 102, 119, 136, 153, 170, 187, 204, 221, 238, 255, 272, 289, 306, 323, 340, 357, 374, 391, 408, 425, 442, 459, 476, 493, 510, 527, 544, 561, 578, 595, 612, 629, 646, 663, 680, 697, 714, 731, 748, 765, 782, 799, 816, 833, 850, 867, 884, 901, 918, 935, 952, 969, 986, 1003, 1020, 1037, 1054, 1071, 1088, 1105, 1122, 1139, 1156, 1173, 1190, 1207, 1224, 1241, 1258, 1275, 1292, 1309, 1326, 1343, 1360, 1377, 1394, 1411, 1428, 1445, 1462, 1479, 1496, 1513, 1530, 1547, 1564, 1581, 1598, 1615, 1632, 1649, 1666, 1683, 1700, 1717, 1734, 1751, 1768, 1785, 1802, 1819, 1836, 1853, 1870, 1887, 1904, 1921, 1938]
---
Traceback (most recent call last):
  File "/openlane/scripts/odbpy/io_place.py", line 429, in <module>
    io_place()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/openlane/scripts/odbpy/reader.py", line 76, in wrapper
    function(**kwargs)
  File "/openlane/scripts/odbpy/io_place.py", line 389, in io_place
    side, pin_placement[side], h_tracks
ValueError: not enough values to unpack (expected 2, got 0)
[ERROR]: during executing: "openroad -exit -no_init -python /openlane/scripts/odbpy/io_place.py --config /openlane/designs/APPROX_MULT/openlane/user_proj_example/pin_order.cfg --hor-layer met3 --ver-layer met2 --ver-width-mult 2 --hor-width-mult 2 --hor-extension -1 --ver-extension -1 --length 4 --input-lef /openlane/designs/APPROX_MULT/runs/RUN_2022.11.16_09.35.48/tmp/merged.nom.lef --output-def /openlane/designs/APPROX_MULT/runs/RUN_2022.11.16_09.35.48/tmp/floorplan/4-io.def --output /openlane/designs/APPROX_MULT/runs/RUN_2022.11.16_09.35.48/tmp/floorplan/4-io.odb /openlane/designs/APPROX_MULT/runs/RUN_2022.11.16_09.35.48/tmp/floorplan/3-initial_fp.odb |& tee >&@stdout /openlane/designs/APPROX_MULT/runs/RUN_2022.11.16_09.35.48/logs/floorplan/4-place_io.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child process exited abnormally

[INFO]: Calculating runtime...
[INFO]: Saving current set of views in 'results/final'...
[INFO]: Generating final set of reports...
[INFO]: Created manufacturability report at 'reports/manufacturability.rpt'.
[INFO]: Created metrics report at 'reports/metrics.csv'.
[INFO]: Saving runtime environment...
[ERROR]: Flow failed.
```

**Comment by vijayank88** [comment]
@donn 
Waiting for your feedback how to proceed further.

**Comment by donn** [comment]
@ZeyadZaki

**Comment by vijayank88** [comment]
@ZeyadZaki 
Its blocking for many of previous MPW CI designs, can you please fix this issue?
