### ISSUE TITLE
OL crashing on stock `spm`

### ISSUE THREAD

**Issue by hpretl** [The-OpenROAD-Project/OpenLane#1991]
### Description

Using latest OL `2023.09.11` this crash is happening in step 31. OL2 runs cleanly through this example.

<img width="1122" alt="image" src="https://github.com/The-OpenROAD-Project/OpenLane/assets/57392031/c3610df2-4fa7-4a80-b8a9-85678861553c">

### Expected Behavior

Clean run until finish.

### Environment report

```shell
/foss/tools/openlane/2023.09 > python3 ./env.py issue-survey
Traceback (most recent call last):
  File "/foss/tools/openlane/2023.09/./env.py", line 265, in <module>
    main()
  File "/foss/tools/openlane/2023.09/./env.py", line 261, in main
    commands[args[0]]()
  File "/foss/tools/openlane/2023.09/./env.py", line 168, in issue_survey
    % get_tag()
  File "/foss/tools/openlane/2023.09/dependencies/get_tag.py", line 72, in get_tag
    raise e
  File "/foss/tools/openlane/2023.09/dependencies/get_tag.py", line 52, in get_tag
    raise NoGitException(
dependencies.get_tag.NoGitException: Cannot determine git branch. Please specify OPENLANE_IMAGE_NAME manually.
Full output: fatal: detected dubious ownership in repository at '/foss/tools/openlane/2023.09'
To add an exception for this directory, call:

	git config --global --add safe.directory /foss/tools/openlane/2023.09
```

### Reproduction material

Use stock `spm`

### Relevant log output

```shell
See above.
```

**Comment by hpretl** [comment]
Ah, now I see. There is a new dependency `libparse`, added it and now it works.
