### ISSUE TITLE
Trying to install openlane locally

### ISSUE THREAD

**Issue by ratul619** [The-OpenROAD-Project/OpenLane#747]
hi , 
triying to install openlane locally , but seems stuck. No idea why the issue is happening.

Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Collecting setuptools-scm>=4
  Using cached setuptools_scm-6.3.2-py3-none-any.whl (33 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.28.3-py3-none-any.whl (884 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-2.0.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from setuptools-scm>=4->matplotlib->-r ./dependencies/python/run_time.txt (line 3)) (44.0.0)
Collecting tomli>=1.0.0
  Using cached tomli-1.2.2-py3-none-any.whl (12 kB)
Installing collected packages: pyparsing, tomli, six, packaging, setuptools-scm, pytz, python-dateutil, pillow, numpy, MarkupSafe, kiwisolver, fonttools, cycler, XlsxWriter, pyyaml, pandas, matplotlib, jinja2, install, click
Successfully installed MarkupSafe-2.0.1 XlsxWriter-3.0.2 click-8.0.3 cycler-0.11.0 fonttools-4.28.3 install-1.3.5 jinja2-2.11.3 kiwisolver-1.3.2 matplotlib-3.5.0 numpy-1.21.4 packaging-21.3 pandas-1.3.4 pillow-8.4.0 pyparsing-3.0.6 python-dateutil-2.8.2 pytz-2021.3 pyyaml-6.0 setuptools-scm-6.3.2 six-1.16.0 tomli-1.2.2
Installing dependencies...

Installing cvc...
HEAD is now at d172016 Update README.md
bash: line 1: y/venv/bin/activate: No such file or directory
Traceback (most recent call last):
  File "./env.py", line 538, in <module>
    main()
  File "./env.py", line 535, in main
    commands[args[0]]()
  File "./env.py", line 418, in local_install
    installer.run()
  File "./env.py", line 404, in run
    install()
  File "./env.py", line 47, in __exit__
    raise exc_value
  File "./env.py", line 404, in run
    install()
  File "./env.py", line 382, in install
    f.write(tool.version_string)
  File "./env.py", line 47, in __exit__
    raise exc_value
  File "./env.py", line 373, in install
    subprocess.run([
  File "./env.py", line 47, in __exit__
    raise exc_value
  File "./env.py", line 373, in install
    subprocess.run([
  File "./env.py", line 47, in __exit__
    raise exc_value
  File "./env.py", line 373, in install
    subprocess.run([
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '-c', '                                    set -e\n                                    source y/venv/bin/activate\n                                    autoreconf -i\n./configure --disable-nls --prefix=$PREFIX\nmake clean\nmake -j$(nproc) $READLINE_CXXFLAGS\nmake install\n\n                                ']' returned non-zero exit status 1.

**Comment by ratul619** [comment]
command run is  "

python3 ./env.py local-install

**Comment by ratul619** [comment]
The whole issue was trying to install in local directory named 'y' .... 

Closing
