### ISSUE TITLE
Could not remove or rename CA certificates during installation

### ISSUE THREAD

**Issue by Louis-DR** [The-OpenROAD-Project/OpenLane#815]
Hello,
I'm facing issues installing OpenLane with the skywater130 package.
I'm trying to install it using the procedure explained in the README. I'm using Ubuntu in WSL2.
When running either `sudo make pdk` or `sudo make full-pdk` I run into the same issue :
<details>
<summary>Error</summary>

```
$ sudo make full-pdk
[sudo] password for louis:
cd /mnt/d/OpenLane/pdks/skywater-pdk && \
        git checkout main && git submodule init && git pull --no-recurse-submodules && \
        git checkout -qf c094b6e83a4f9298e47f696ec5a7fd53535ec5eb
Previous HEAD position was c094b6e Merge pull request #333 from donn/patch-1
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
cd /mnt/d/OpenLane/pdks/skywater-pdk && \
        git submodule update --init libraries/sky130_fd_sc_hd/latest && \
        git submodule update --init libraries/sky130_fd_sc_hs/latest && \
        git submodule update --init libraries/sky130_fd_sc_hdll/latest && \
        git submodule update --init libraries/sky130_fd_sc_ms/latest && \
        git submodule update --init libraries/sky130_fd_sc_ls/latest && \
        git submodule update --init libraries/sky130_fd_sc_hvl/latest && \
        git submodule update --init libraries/sky130_fd_io/latest && \
        make -j8 timing
make[1]: Entering directory '/mnt/d/OpenLane/pdks/skywater-pdk'
cd /mnt/d/OpenLane/pdks/skywater-pdk; git submodule update --init third_party/make-env
chmod a+x /mnt/d/OpenLane/pdks/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh
/mnt/d/OpenLane/pdks/skywater-pdk/env/downloads/Miniconda3-latest-Linux-x86_64.sh -p /mnt/d/OpenLane/pdks/skywater-pdk/env/conda -b -f
PREFIX=/mnt/d/OpenLane/pdks/skywater-pdk/env/conda
Unpacking payload ...
Extracting : _libgcc_mutex-0.1-main.conda:   3%|████▎                                                                                                                                                                | 1/38 [00:01<00:58,  1.58s/it]
Could not remove or rename /mnt/d/OpenLane/pdks/skywater-pdk/env/conda/pkgs/ca-certificates-2021.7.5-h06a4308_1mnu67k09/pkg-ca-certificates-2021.7.5-h06a4308_1.tar.zst.  Please remove this file manually (you may need to reboot to free file handles)
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 368, in _queue_management_worker
  File "multiprocessing/connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 611, in result_iterator
  File "concurrent/futures/_base.py", line 439, in result
  File "concurrent/futures/_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[4407] Failed to execute script entry_point
make[1]: *** [/mnt/d/OpenLane/pdks/skywater-pdk/third_party/make-env/conda.mk:128: /mnt/d/OpenLane/pdks/skywater-pdk/env/conda/bin/python] Error 1
make[1]: Leaving directory '/mnt/d/OpenLane/pdks/skywater-pdk'
make: *** [Makefile:127: all-skywater-libraries] Error 2
```

</details>

This CA certificate file is created during the flow and I could not locate where to add a `rm` in the Makefiles.
I also tried searching if this was an issue with Conda itself but it doesn't appear to be the case.

Has anyone encountered this issue or is this a known problem ?

Thank you very much

**Comment by donn** [comment]
See #806
